/**
 * users table
 *
 * Rename "user" → whatever entity your app uses (e.g. "organization", "tenant", "player").
 * Add / remove columns to match your domain.
 */

import { boolean, pgEnum, pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

// ── Enums ─────────────────────────────────────────────────────────────────────
// TODO: rename/extend to match your app's user roles or tiers
export const planEnum = pgEnum('plan', ['free', 'pro']);

// ── Table ─────────────────────────────────────────────────────────────────────
export const users = pgTable('users', {
  // Primary key — UUID v4 generated by the DB
  id: uuid('id').defaultRandom().primaryKey(),

  // TODO: rename to match your entity (e.g. "companyName", "teamName", "fullName")
  name: text('name').notNull(),

  email: text('email').notNull().unique(),

  // Stored as bcrypt hash — never expose raw password
  passwordHash: text('password_hash').notNull(),

  // Hashed refresh token — null when logged out
  refreshTokenHash: text('refresh_token_hash'),

  // TODO: keep/replace/extend plan enum for your business model
  plan: planEnum('plan').default('free').notNull(),

  lastLoginAt: timestamp('last_login_at', { withTimezone: true }),

  // TODO: add/remove notification preference columns your app needs
  notifyOnHighPriority: boolean('notify_on_high_priority').default(true).notNull(),
  notifyDigest: boolean('notify_digest').default(false).notNull(),

  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});
